#!/usr/bin/env python3
"""Run the SATROOT-1 conformance corpus against any implementation.

    python3 run.py                      # against the reference (sanity check)
    python3 run.py --impl "./my-verify" # against yours
    python3 run.py --impl "..." --emit > mine.txt && diff mine.txt EXPECTED.txt

Stdlib only, no dependencies, Python 3.8+. Copy this file and the *.json
vectors anywhere; nothing else is needed.

--------------------------------------------------------------------------
THE ADAPTER CONTRACT
--------------------------------------------------------------------------
Your implementation is invoked once per vector:

    <your command> /path/to/some-vector.json

Read the file, replay its `events` array under its `scheme` (fixed key
material is documented in README.md), and print ONE line to stdout:

    ACCEPT <final_state_hash> <record_count> <account>=<balance> ...
    REJECT

Accounts in any order (this runner sorts them). Exit status is ignored;
only stdout is read, and only its last non-empty line. Anything on stderr
is shown when a vector fails, so debug output there is free.

Print REJECT when replay must fail. That is not an error condition: 21 of
the 33 vectors are rejection cases, and refusing them correctly is most of
what conformance means.

--------------------------------------------------------------------------
WHERE EXPECTED.txt COMES FROM
--------------------------------------------------------------------------
It is derived from the `expect` block declared inside each vector file,
NOT from executing the reference implementation. If it were generated by
running the reference, an "independent" implementation would be diffing
against output produced by the code under test, and agreement would prove
nothing. Regenerate with --write-expected; it reads only the JSON.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
EXPECTED_PATH = HERE / "EXPECTED.txt"


# --------------------------------------------------------------------------
# the one canonical result line
# --------------------------------------------------------------------------

def format_result(ok, state_hash=None, record_count=None, balances=None):
    """Render one outcome as the single line this corpus compares on."""
    if not ok:
        return "REJECT"
    parts = ["ACCEPT", str(state_hash), str(record_count)]
    for account in sorted(balances or {}):
        parts.append("%s=%s" % (account, balances[account]))
    return " ".join(parts)


def expected_line(vector):
    """Derive the expected result from the vector's own declared `expect`."""
    expect = vector["expect"]
    if not expect.get("ok"):
        return format_result(False)
    return format_result(
        True,
        expect["final_state_hash"],
        expect["record_count"],
        expect.get("balances", {}),
    )


def normalise(line):
    """Sort balance terms so account order in an adapter's output is free."""
    fields = line.strip().split()
    if not fields or fields[0] != "ACCEPT":
        return line.strip()
    return " ".join(fields[:3] + sorted(fields[3:]))


# --------------------------------------------------------------------------
# runners
# --------------------------------------------------------------------------

def run_external(command, path):
    """Invoke the operator's implementation on one vector.

    The path is quoted: a checkout under a directory with a space in it
    (C:\\Users\\Foo Bar\\... is entirely ordinary) would otherwise arrive as
    two arguments and fail on every vector.
    """
    proc = subprocess.run(
        '%s "%s"' % (command, str(path)),
        shell=True,
        capture_output=True,
        text=True,
    )
    lines = [ln for ln in proc.stdout.splitlines() if ln.strip()]
    if not lines:
        detail = proc.stderr.strip() or "(no stderr)"
        return None, "printed nothing to stdout; stderr: %s" % detail[:400]
    return normalise(lines[-1]), None


def load_reference():
    """Import the reference implementation, from the repo or an install."""
    for candidate in (HERE.parent / "src", HERE.parent):
        if (candidate / "satroot1.py").exists():
            sys.path.insert(0, str(candidate))
            break
    try:
        import satroot1
    except ImportError:
        return None
    return satroot1


FIXED_ED25519_PRIVATE = {"issuer-key": "11" * 32, "alice-key": "22" * 32}
FIXED_HMAC_SECRETS = {"issuer-key": "33" * 32, "alice-key": "44" * 32}


def run_reference(sr, vector):
    scheme = vector["scheme"]
    if scheme == "demo":
        verifier = sr.demo_signature_verifier
    elif scheme == "ed25519":
        verifier = sr.make_ed25519_verifier(
            sr.derive_ed25519_public_keys(FIXED_ED25519_PRIVATE)
        )
    elif scheme == "hmac-sha256":
        verifier = sr.make_hmac_sha256_verifier(FIXED_HMAC_SECRETS)
    else:
        return None, "unknown scheme in vector: %s" % scheme
    try:
        state = sr.replay(vector["events"], verifier=verifier)
    except sr.SatRootError:
        return format_result(False), None
    return (
        format_result(
            True,
            state.state_hash(),
            len(vector["events"]),
            state.snapshot()["balances"],
        ),
        None,
    )


# --------------------------------------------------------------------------

def vector_paths():
    paths = sorted(HERE.glob("*.json"))
    if not paths:
        sys.exit("no vectors found beside %s" % __file__)
    return paths


def main():
    parser = argparse.ArgumentParser(
        description="Run the SATROOT-1 conformance corpus.",
        epilog="With no --impl, runs the reference implementation.",
    )
    parser.add_argument(
        "--impl",
        metavar="CMD",
        help="command to invoke per vector; receives the vector path as its "
             "one argument and prints one ACCEPT/REJECT line to stdout",
    )
    parser.add_argument(
        "--emit",
        action="store_true",
        help="print result lines only, for diffing against EXPECTED.txt",
    )
    parser.add_argument(
        "--write-expected",
        action="store_true",
        help="regenerate EXPECTED.txt from the vectors' declared expectations",
    )
    args = parser.parse_args()

    if args.emit:
        # EXPECTED.txt is LF-terminated, and print() would emit CRLF on
        # Windows - making every line of the diff differ for no reason.
        try:
            sys.stdout.reconfigure(newline="\n")
        except AttributeError:  # Python < 3.7
            pass

    paths = vector_paths()
    vectors = [(p, json.loads(p.read_text(encoding="utf-8"))) for p in paths]

    if args.write_expected:
        body = "".join(
            "%s %s\n" % (p.name, expected_line(v)) for p, v in vectors
        )
        with open(EXPECTED_PATH, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(body)
        print("wrote %s (%d vectors)" % (EXPECTED_PATH.name, len(vectors)))
        return 0

    sr = None
    if not args.impl:
        sr = load_reference()
        if sr is None:
            sys.exit(
                "reference implementation not importable.\n"
                "Either run inside the satroot repository, or `pip install "
                "satroot`, or test your own with --impl."
            )

    failures = []
    for path, vector in vectors:
        want = expected_line(vector)
        if args.impl:
            got, error = run_external(args.impl, path)
        else:
            got, error = run_reference(sr, vector)

        if args.emit:
            print("%s %s" % (path.name, got if got is not None else "ERROR"))
            continue

        if error is not None:
            failures.append((path.name, error))
            print("FAIL %s\n       %s" % (path.name, error))
        elif got != want:
            failures.append((path.name, "expected %r, got %r" % (want, got)))
            print("FAIL %s\n       expected: %s\n       got:      %s"
                  % (path.name, want, got))
        else:
            print("ok   %s" % path.name)

    if args.emit:
        return 0

    print("\n%d vectors, %d failures" % (len(vectors), len(failures)))
    if failures:
        print(
            "\nA failure here is worth reporting even if it turns out to be "
            "mine:\nhttps://github.com/parthod0x/satroot/issues"
        )
        return 1
    if args.impl:
        print(
            "\nAll %d matched. If you are willing to be named as having run "
            "this\nindependently, that would be the first external "
            "verification the\nproject has had - please say so on the issue "
            "tracker or by email." % len(vectors)
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
